version: '3'

services:
  client:
    container_name: jernawebapp
    build: ..
    ports:
      - 8975:8080
    depends_on:
      - db
    healthcheck:
      test: wget --tries=1 http://localhost:8080/health || exit 1
      interval: 2s
      retries: 1
      start_period: 6s
      timeout: 1s
    environment:
      # - ENVIRONMENT = 
      - db=user id=jernaadmin;database=jernadb;password=fnbsduif438cbsduicna7683r;host=jernapostgres
      - emailpassword=$EMAIL_PASSWORD
    networks:
      otel: 

  db:
    container_name: jernapostgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jernaadmin
      POSTGRES_DB: jernadb
      POSTGRES_PASSWORD: fnbsduif438cbsduicna7683r
    volumes:
     - ../JernaIntegrationTests/20240409.05.27.45.sql:/docker-entrypoint-initdb.d/a_init.sql
    networks:
        otel: 

  blackbox:
    container_name: jernablackbox
    # https://github.com/prometheus/blackbox_exporter/releases
    image: prom/blackbox-exporter:v0.23.0
    restart: unless-stopped
    ports:
      - 9151:9115
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../JernaWebApp/JernaTelemetry/blackbox/blackbox.yml:/etc/blackbox/blackbox.yml
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      otel:

  prometheus:
    container_name: jernaprometheus
    # https://github.com/prometheus/prometheus/releases
    image: prom/prometheus:v2.43.0
    hostname: prometheus
    restart: unless-stopped
    ports:
        - 9097:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../JernaWebApp/JernaTelemetry/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
        - blackbox 
    networks:
      otel: 
  
  zipkin:
    container_name: jernazipkin
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9141:9411
    networks:
      otel: 

  grafana:
    container_name: jernagrafana
    # https://github.com/grafana/grafana/releases
    image: grafana/grafana:9.4.7
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ../JernaWebApp/JernaTelemetry/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    user: root
    ports:
      - "3090:3000"
    depends_on:
      - prometheus 
      - loki
    networks:
      otel: 
      
      
  loki:
    container_name: jernaloki
    # https://github.com/grafana/loki/releases
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /etc/localtime:/etc/localtime:ro      
      - ../JernaWebApp/JernaTelemetry/loki/loki.yml:/etc/loki/local-config.yaml
      - loki:/data/loki
    restart: unless-stopped
    ports:
      - 30013:3100
    networks:
      otel:

  otel-collector:
    container_name: jernaotel-collector
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/releases
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.75.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ../JernaWebApp/JernaTelemetry/otel/otel.yml:/etc/otel-collector-config.yaml
    restart: unless-stopped
    ports:
      - 10083:8888   # Prometheus metrics exposed by the collector
      - 8389:8889   # Prometheus exporter metrics
      - 4347:4317   # OTLP gRPC receiver
      - 9020:55679  # zpages
      - 43333:13133 # Health check
    networks:
      otel: 

  # proxy:
  #   image: nginx
  #   depends_on:
  #     - webapitruservice
  #     - grafana
  #   container_name: dorian-proxy
  #   ports:
  #    - 5937:80
  #   volumes:
  #    - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     otel:


  swag:
    image: lscr.io/linuxserver/swag
    container_name: jernaswag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=jernadocker.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=55c6f3a0-5530-4df8-b939-58b27a9cb991
      - STAGING=true
    volumes:
      - swag_data:/config
      - ./nginx-default.conf:/config/nginx/site-confs/default.conf
    ports:
      - 4443:443
    restart: unless-stopped
    

  node-exporter:
    container_name: jernanode-exporter
    image: prom/node-exporter:latest
    ports:
      - 9450:9100
    networks:
      - monitoring

networks:
  otel:
  monitoring:
    driver: bridge

volumes:
  prometheus:
  prometheus-data:
  grafana-data:
  swag_data:
  loki:

  


