receivers:
  otlp:
    protocols:
      grpc:
      http:
      # zipkin:

exporters:
  # otlp:
  #   endpoint: tempo:4007
  # zipkin: 
  #   endpoint: http://zipkin:9411/api/v2/spans
  prometheus:
    endpoint: otel:8889
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

extensions:
  # health_check:
  # zpages:
  #    endpoint: otel:55679

processors:
  # Data sources: traces, metrics, logs
  batch:

service:
  # extensions: [zpages, health_check]  # Enable zpages
  pipelines:
    logs:
      receivers: [otlp]
      processors: []
      exporters: [loki]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [otlp, zipkin]


otel-collector:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/releases
  hostname: otel
  image: otel/opentelemetry-collector-contrib:0.75.0
  command: ["--config=/etc/otel-collector-config.yaml"]
  volumes:
    - ../JernaSchools/JernaWebApp/JernaTelemetry/otel/otel.yml:/etc/otel-collector-config.yaml
  restart: unless-stopped
  ports:
    - 10083:8888   # Prometheus metrics exposed by the collector
    - 8389:8889   # Prometheus exporter metrics
    - 4347:4317   # OTLP gRPC receiver
    - 9020:55679  # zpages
    - 43333:13133 # Health check
  networks:
    otel: 

loki:
  # https://github.com/grafana/loki/releases
  image: grafana/loki:2.8.0
  command: -config.file=/etc/loki/local-config.yaml
  volumes:
    - /etc/localtime:/etc/localtime:ro      
    - ..JernaSchools/JernaWebApp/JernaTelemetry/loki/loki.yml:/etc/loki/local-config.yaml
    - loki:/data/loki
  restart: unless-stopped
  ports:
    - 30013:3100
  networks:
    otel: