name: take down pull request environment
on: 
  pull_request: 
    types: [closed]
jobs:
  deploy-to-kubernetes:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: deploy to kubernetes
        run: |
          export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
          export NAMESPACE="jerna-pr-$PULL_REQUEST_ID"
          kubectl delete namespace $NAMESPACE
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey there, chump. Took down pull request environment at <http://${{ github.event.pull_request.number }}.jernaschools.duckdns.org>'
            });

#adding pootis
    
